baseURL: http://example.org/
languageCode: en-us
title: ProDeSquare

theme: novela

paginate: 6

social:
  twitter: "https://twitter.com/ProDeSquare"
  github: "https://github.com/ProDeSquare"
  instagram: "https://instagram.com/ProDeSquare"
  youtube: "https://youtube.com/ProDeSquare"

taxonomies:
  author: authors
