baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

theme: novela

paginate: 6

social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"

taxonomies:
  author: authors
